FROM openjdk:17-jdk-slim
WORKDIR /app

# 复制本地构建好的jar文件
COPY target/exam1-0.0.1-SNAPSHOT.jar app.jar

# 设置时区
ENV TZ=Asia/Shanghai

# 暴露端口
EXPOSE 8081

# 启动应用，使用Docker配置文件
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=docker", "app.jar"]